import { Project } from '../types';
import { normalizeProjectDates, rpnTotal, tryIso } from './ProjectUtils';

// Must match the Status Choice values on the SharePoint RCM Register list exactly.
export const RCM_STATUS_OPTIONS = [
    'Data Gathering',
    'FMECA',
    'Consequence Classification',
    'RCM Report Drafting',
    'Attached Report',
];

// SharePoint's "Multiple lines of text" (plain text, no append) holds 63,999 characters.
// Stay just under it — the earlier 2,000 cap was ours, not the list's, and truncated summaries.
const SUMMARY_MAX_CHARS = 60000;
const TRUNCATION_SUFFIX = '…(truncated)';

export interface RcmRegisterPayload {
    system: string;             // list column: System
    subSystems: string;         // multiline, one per line
    startDate: string;          // ISO 8601 UTC
    engineerName: string;       // email / UPN (Person column needs this, not a display name)
    status: string;             // must match a list Choice value exactly
    summaryOfActions: string;
    fileName: string;
    fileContentBase64: string;  // raw base64, no data: prefix
    jsonFileName: string;
    jsonContentBase64: string;  // raw base64, no data: prefix
}

export interface RcmRegisterResult {
    rcmInternalNumber: string;  // generated BY THE FLOW, e.g. RCM-2026-02
    itemId: number;
    itemLink: string;
}

export interface BuildRegisterPayloadOptions {
    engineerEmail: string;
    status: string;
    startDate: string;
    summaryOfActions: string;
    fileName: string;
    fileContentBase64: string;
    jsonFileName: string;
    jsonContentBase64: string;
}

/** Creation date of a project as ISO 8601 UTC, tolerating the `created`/`createdAt` split. */
export function projectStartIso(project: Project): string {
    const normalized = normalizeProjectDates(project as any);
    return tryIso(normalized.createdAt) || new Date().toISOString();
}

/** `YYYY-MM-DD` for an `<input type="date">`, derived from the project's creation date. */
export function projectStartDateInput(project: Project): string {
    return projectStartIso(project).slice(0, 10);
}

/** Sub-system names, deduped, blanks dropped, source order preserved. */
export function subSystemNames(project: Project): string[] {
    const seen = new Set<string>();
    const names: string[] = [];
    (project.subsystems || []).forEach(s => {
        const name = (s?.name || '').trim();
        if (!name || seen.has(name)) return;
        seen.add(name);
        names.push(name);
    });
    return names;
}

/** Numbered one per line — "1- Pump Assembly" — as the register list expects. */
export function buildSubSystemsList(project: Project): string {
    return subSystemNames(project).map((name, i) => `${i + 1}- ${name}`).join('\n');
}

/** Rollup of every mode mitigation across the project, ordered by descending RPN total. */
export function buildSummaryOfActions(project: Project): string {
    const best = new Map<string, number>();
    (project.subsystems || []).forEach(sub => {
        (sub.failures || []).forEach(fail => {
            (fail.modes || []).forEach(mode => {
                const text = (mode?.mitigation || '').trim();
                if (!text) return;
                const total = rpnTotal(mode.rpn);
                const score = typeof total === 'number' ? total : 0;
                const prev = best.get(text);
                if (prev === undefined || score > prev) best.set(text, score);
            });
        });
    });
    const ordered = [...best.entries()].sort((a, b) => b[1] - a[1]).map(([text]) => text);
    return capText(ordered.join('\n'), SUMMARY_MAX_CHARS);
}

/**
 * Flattened controls/mitigations, highest RPN first — the input the AI summarizes.
 * Modes with neither a control nor a mitigation carry no action, so they are dropped.
 */
export function buildActionsInput(project: Project): string {
    const rows: { score: number; text: string }[] = [];
    (project.subsystems || []).forEach(sub => {
        (sub.failures || []).forEach(fail => {
            (fail.modes || []).forEach(mode => {
                const controls = (mode?.currentControls || '').trim();
                const mitigation = (mode?.mitigation || '').trim();
                if (!controls && !mitigation) return;
                const total = rpnTotal(mode.rpn);
                const score = typeof total === 'number' ? total : 0;
                rows.push({
                    score,
                    text: [
                        `SUB-SYSTEM: ${(sub.name || '').trim() || '(unnamed)'}`,
                        `FUNCTIONAL FAILURE: ${(fail.desc || '').trim() || '(none)'}`,
                        `FAILURE MODE: ${(mode.mode || '').trim() || '(none)'}`,
                        `RPN: ${score || 'unscored'}`,
                        `CURRENT CONTROLS (already in place): ${controls || '(none)'}`,
                        `RECOMMENDED MITIGATION (not yet in place): ${mitigation || '(none)'}`,
                    ].join('\n'),
                });
            });
        });
    });
    return rows.sort((a, b) => b.score - a.score).map(r => r.text).join('\n\n');
}

export const SUMMARY_SYSTEM_PROMPT = `You are a senior reliability engineer writing the "Summary of Actions" entry for an RCM register.

You receive failure modes with two distinct fields:
- CURRENT CONTROLS — maintenance and monitoring ALREADY being performed. These continue.
- RECOMMENDED MITIGATION — barriers NOT yet in place. These are new work to implement.

Write plain text (no markdown, no bold, no headers with #) in exactly this shape:

CONTINUE (existing controls)
1- <short line, one per distinct control>
2- ...

IMPLEMENT (new actions)
1- <action in detail: what to do, on which sub-system/equipment, and the failure mode it defends against>
2- ...

Rules:
- CONTINUE items are terse — a few words each, merged where several modes share the same control.
- IMPLEMENT items are detailed and specific enough to raise a work order from, and are ordered by descending RPN (highest risk first).
- Merge duplicates across sub-systems instead of repeating them; name the sub-systems the merged item covers.
- Never invent an action that is not in the input. Never move a mitigation into CONTINUE or a control into IMPLEMENT.
- If a section has no items, write the heading and "None." beneath it.
- Output only the summary text — no preamble, no closing remarks.`;

/**
 * Instructions and data in ONE prompt: AIService._directChat only forwards messages[0]
 * for non-chatbot features, so a separate system message would be dropped.
 */
export function buildSummaryPrompt(project: Project): string {
    return `${SUMMARY_SYSTEM_PROMPT}\n\nSYSTEM: ${project.name || '(unnamed)'}\n\n${buildActionsInput(project)}`;
}

/** btoa() is latin1-only, so encode to UTF-8 bytes first (project text may be non-ASCII). */
export function toBase64Utf8(text: string): string {
    const bytes = new TextEncoder().encode(text);
    const CHUNK = 0x8000; // stay under the argument limit of String.fromCharCode
    let binary = '';
    for (let i = 0; i < bytes.length; i += CHUNK) binary += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
    return btoa(binary);
}

/** Same payload as the "Export" button — the normalized project as JSON, base64 encoded. */
export function buildProjectJsonBase64(project: Project): string {
    return toBase64Utf8(JSON.stringify(normalizeProjectDates(project as any)));
}

function capText(text: string, max: number): string {
    if (text.length <= max) return text;
    return text.slice(0, Math.max(0, max - TRUNCATION_SUFFIX.length)) + TRUNCATION_SUFFIX;
}

/** Pure mapping from FMECA project + form values to the flow payload. */
export function buildRegisterPayload(project: Project, opts: BuildRegisterPayloadOptions): RcmRegisterPayload {
    const summary = opts.summaryOfActions.trim() || buildSummaryOfActions(project);
    return {
        system: project.name || '',
        subSystems: buildSubSystemsList(project),
        startDate: tryIso(opts.startDate) || projectStartIso(project),
        engineerName: opts.engineerEmail.trim(),
        status: opts.status,
        summaryOfActions: capText(summary, SUMMARY_MAX_CHARS),
        fileName: opts.fileName,
        fileContentBase64: opts.fileContentBase64,
        jsonFileName: opts.jsonFileName,
        jsonContentBase64: opts.jsonContentBase64,
    };
}

/**
 * POSTs one row to the Power Automate flow backing the SharePoint RCM register.
 * The flow — not this app — computes the RCM internal number and returns it.
 */
export async function publishToRcmRegister(flowUrl: string, payload: RcmRegisterPayload): Promise<RcmRegisterResult> {
    if (!flowUrl.trim()) throw new Error('Set the RCM Register flow URL in Settings.');

    // Body is JSON, but the Content-Type is text/plain on purpose: it keeps this a CORS
    // "simple request" so the browser skips the preflight. Power Automate's HTTP trigger
    // does not answer OPTIONS, so an application/json POST never reaches the flow.
    // The flow must therefore parse the body with json(triggerBody()).
    const res = await fetch(flowUrl.trim(), {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain;charset=UTF-8' },
        body: JSON.stringify(payload),
    });

    if (!res.ok) {
        const body = await res.text().catch(() => '');
        throw new Error(`RCM Register error: HTTP ${res.status} ${res.statusText}. ${body}`);
    }

    const raw = await res.text();
    let parsed: any;
    try { parsed = JSON.parse(raw); } catch {
        throw new Error(`RCM Register error: flow reply was not JSON. Raw response: ${raw}`);
    }

    const rcmInternalNumber = String(parsed?.rcmInternalNumber ?? '').trim();
    const itemId = Number(parsed?.itemId);
    if (!rcmInternalNumber || !Number.isFinite(itemId)) {
        throw new Error(`RCM Register error: flow reply missing rcmInternalNumber or itemId. Raw response: ${raw}`);
    }

    return { rcmInternalNumber, itemId, itemLink: String(parsed?.itemLink ?? '') };
}
