import { Project } from '../types';
import { normalizeProjectDates, rpnTotal, tryIso } from './ProjectUtils';

// Must match the Status Choice values on the SharePoint RCM Register list exactly.
export const RCM_STATUS_OPTIONS = [
    'Data Gathering',
    'FMECA',
    'Consequence Classification',
    'RCM Report Drafting',
    'Attached Report',
];

// SharePoint's "Multiple lines of text" (plain text, no append) holds 63,999 characters.
// Stay just under it — the earlier 2,000 cap was ours, not the list's, and truncated summaries.
const SUMMARY_MAX_CHARS = 60000;
const TRUNCATION_SUFFIX = '…(truncated)';

export interface RcmRegisterPayload {
    action: 'create';           // flow switches on this; absent means "create" for older flows
    system: string;             // list column: System
    subSystems: string;         // multiline, one per line
    startDate: string;          // ISO 8601 UTC
    engineerName: string;       // email / UPN (Person column needs this, not a display name)
    status: string;             // must match a list Choice value exactly
    summaryOfActions: string;
    fileName: string;
    fileContentBase64: string;  // raw base64, no data: prefix
    jsonFileName: string;
    jsonContentBase64: string;  // raw base64, no data: prefix
}

export interface RcmRegisterResult {
    rcmInternalNumber: string;  // generated BY THE FLOW, e.g. RCM-2026-02
    itemId: number;
    itemLink: string;
}

/** One register row as shown in the "open from SharePoint" picker. */
export interface RcmRegisterRow {
    itemId: number;
    rcmInternalNumber: string;
    system: string;
    status: string;
    engineerName: string;
    startDate: string;
    /** Name of the FMECA JSON attachment, when the flow reports it. */
    jsonFileName: string;
}

/**
 * Where the register lives, for the generic SharePoint Reader flow. That flow is
 * list-agnostic — it takes the site and list per request and returns raw SharePoint
 * fields — so the app owns this mapping rather than the flow.
 *
 * Internal names come from the reader's own `schema` action; note the RCM internal
 * number is stored in the built-in `Title` column, not a custom one.
 */
export const REGISTER_LIST = {
    site: 'https://oxyinc.sharepoint.com/sites/AIProduction',
    list: 'RCM List',
    columns: {
        rcmInternalNumber: 'Title',
        system: 'System',
        subSystems: 'Sub_x002d_Systems',
        startDate: 'StartDate',
        engineerName: 'EngineerName',   // Person column — needs $expand to read the email
        status: 'Status',
        summaryOfActions: 'SummaryofActions',
    },
} as const;

export interface BuildRegisterPayloadOptions {
    engineerEmail: string;
    status: string;
    startDate: string;
    summaryOfActions: string;
    fileName: string;
    fileContentBase64: string;
    jsonFileName: string;
    jsonContentBase64: string;
}

/** Creation date of a project as ISO 8601 UTC, tolerating the `created`/`createdAt` split. */
export function projectStartIso(project: Project): string {
    const normalized = normalizeProjectDates(project as any);
    return tryIso(normalized.createdAt) || new Date().toISOString();
}

/** `YYYY-MM-DD` for an `<input type="date">`, derived from the project's creation date. */
export function projectStartDateInput(project: Project): string {
    return projectStartIso(project).slice(0, 10);
}

/** Sub-system names, deduped, blanks dropped, source order preserved. */
export function subSystemNames(project: Project): string[] {
    const seen = new Set<string>();
    const names: string[] = [];
    (project.subsystems || []).forEach(s => {
        const name = (s?.name || '').trim();
        if (!name || seen.has(name)) return;
        seen.add(name);
        names.push(name);
    });
    return names;
}

/** Numbered one per line — "1- Pump Assembly" — as the register list expects. */
export function buildSubSystemsList(project: Project): string {
    return subSystemNames(project).map((name, i) => `${i + 1}- ${name}`).join('\n');
}

/** Rollup of every mode mitigation across the project, ordered by descending RPN total. */
export function buildSummaryOfActions(project: Project): string {
    const best = new Map<string, number>();
    (project.subsystems || []).forEach(sub => {
        (sub.failures || []).forEach(fail => {
            (fail.modes || []).forEach(mode => {
                const text = (mode?.mitigation || '').trim();
                if (!text) return;
                const total = rpnTotal(mode.rpn);
                const score = typeof total === 'number' ? total : 0;
                const prev = best.get(text);
                if (prev === undefined || score > prev) best.set(text, score);
            });
        });
    });
    const ordered = [...best.entries()].sort((a, b) => b[1] - a[1]).map(([text]) => text);
    return capText(ordered.join('\n'), SUMMARY_MAX_CHARS);
}

/**
 * Flattened controls/mitigations, highest RPN first — the input the AI summarizes.
 * Modes with neither a control nor a mitigation carry no action, so they are dropped.
 */
export function buildActionsInput(project: Project): string {
    const rows: { score: number; text: string }[] = [];
    (project.subsystems || []).forEach(sub => {
        (sub.failures || []).forEach(fail => {
            (fail.modes || []).forEach(mode => {
                const controls = (mode?.currentControls || '').trim();
                const mitigation = (mode?.mitigation || '').trim();
                if (!controls && !mitigation) return;
                const total = rpnTotal(mode.rpn);
                const score = typeof total === 'number' ? total : 0;
                rows.push({
                    score,
                    text: [
                        `SUB-SYSTEM: ${(sub.name || '').trim() || '(unnamed)'}`,
                        `FUNCTIONAL FAILURE: ${(fail.desc || '').trim() || '(none)'}`,
                        `FAILURE MODE: ${(mode.mode || '').trim() || '(none)'}`,
                        `RPN: ${score || 'unscored'}`,
                        `CURRENT CONTROLS (already in place): ${controls || '(none)'}`,
                        `RECOMMENDED MITIGATION (not yet in place): ${mitigation || '(none)'}`,
                    ].join('\n'),
                });
            });
        });
    });
    return rows.sort((a, b) => b.score - a.score).map(r => r.text).join('\n\n');
}

export const SUMMARY_SYSTEM_PROMPT = `You are a senior reliability engineer writing the "Summary of Actions" entry for an RCM register.

You receive failure modes with two distinct fields:
- CURRENT CONTROLS — maintenance and monitoring ALREADY being performed. These continue.
- RECOMMENDED MITIGATION — barriers NOT yet in place. These are new work to implement.

Write plain text (no markdown, no bold, no headers with #) in exactly this shape:

CONTINUE (existing controls)
1- <short line, one per distinct control>
2- ...

IMPLEMENT (new actions)
1- <action in detail: what to do, on which sub-system/equipment, and the failure mode it defends against>
2- ...

Rules:
- CONTINUE items are terse — a few words each, merged where several modes share the same control.
- IMPLEMENT items are detailed and specific enough to raise a work order from, and are ordered by descending RPN (highest risk first).
- Merge duplicates across sub-systems instead of repeating them; name the sub-systems the merged item covers.
- Never invent an action that is not in the input. Never move a mitigation into CONTINUE or a control into IMPLEMENT.
- If a section has no items, write the heading and "None." beneath it.
- Output only the summary text — no preamble, no closing remarks.`;

/**
 * Instructions and data in ONE prompt: AIService._directChat only forwards messages[0]
 * for non-chatbot features, so a separate system message would be dropped.
 */
export function buildSummaryPrompt(project: Project): string {
    return `${SUMMARY_SYSTEM_PROMPT}\n\nSYSTEM: ${project.name || '(unnamed)'}\n\n${buildActionsInput(project)}`;
}

/** btoa() is latin1-only, so encode to UTF-8 bytes first (project text may be non-ASCII). */
export function toBase64Utf8(text: string): string {
    const bytes = new TextEncoder().encode(text);
    const CHUNK = 0x8000; // stay under the argument limit of String.fromCharCode
    let binary = '';
    for (let i = 0; i < bytes.length; i += CHUNK) binary += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
    return btoa(binary);
}

/** Same payload as the "Export" button — the normalized project as JSON, base64 encoded. */
export function buildProjectJsonBase64(project: Project): string {
    return toBase64Utf8(JSON.stringify(normalizeProjectDates(project as any)));
}

function capText(text: string, max: number): string {
    if (text.length <= max) return text;
    return text.slice(0, Math.max(0, max - TRUNCATION_SUFFIX.length)) + TRUNCATION_SUFFIX;
}

/** Pure mapping from FMECA project + form values to the flow payload. */
export function buildRegisterPayload(project: Project, opts: BuildRegisterPayloadOptions): RcmRegisterPayload {
    const summary = opts.summaryOfActions.trim() || buildSummaryOfActions(project);
    return {
        action: 'create',
        system: project.name || '',
        subSystems: buildSubSystemsList(project),
        startDate: tryIso(opts.startDate) || projectStartIso(project),
        engineerName: opts.engineerEmail.trim(),
        status: opts.status,
        summaryOfActions: capText(summary, SUMMARY_MAX_CHARS),
        fileName: opts.fileName,
        fileContentBase64: opts.fileContentBase64,
        jsonFileName: opts.jsonFileName,
        jsonContentBase64: opts.jsonContentBase64,
    };
}

/**
 * POSTs one request to the Power Automate flow backing the SharePoint RCM register and
 * returns its parsed JSON reply. Every action (create / list / fetch) shares this URL;
 * the flow switches on `action`.
 */
async function postToFlow(flowUrl: string, body: unknown): Promise<any> {
    if (!flowUrl.trim()) throw new Error('Set the RCM Register flow URL in Settings.');

    // Body is JSON, but the Content-Type is text/plain on purpose: it keeps this a CORS
    // "simple request" so the browser skips the preflight. Power Automate's HTTP trigger
    // does not answer OPTIONS, so an application/json POST never reaches the flow.
    // The flow must therefore parse the body with json(triggerBody()).
    const res = await fetch(flowUrl.trim(), {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain;charset=UTF-8' },
        body: JSON.stringify(body),
    });

    if (!res.ok) {
        const text = await res.text().catch(() => '');
        throw new Error(`RCM Register error: HTTP ${res.status} ${res.statusText}. ${text}`);
    }

    const raw = await res.text();
    try { return JSON.parse(raw); } catch {
        throw new Error(`RCM Register error: flow reply was not JSON. Raw response: ${raw}`);
    }
}

/**
 * POSTs one row to the Power Automate flow backing the SharePoint RCM register.
 * The flow — not this app — computes the RCM internal number and returns it.
 */
export async function publishToRcmRegister(flowUrl: string, payload: RcmRegisterPayload): Promise<RcmRegisterResult> {
    const parsed = await postToFlow(flowUrl, payload);
    const rcmInternalNumber = String(parsed?.rcmInternalNumber ?? '').trim();
    const itemId = Number(parsed?.itemId);
    if (!rcmInternalNumber || !Number.isFinite(itemId)) {
        throw new Error(`RCM Register error: flow reply missing rcmInternalNumber or itemId. Raw response: ${JSON.stringify(parsed)}`);
    }
    return { rcmInternalNumber, itemId, itemLink: String(parsed?.itemLink ?? '') };
}

const C = REGISTER_LIST.columns;

/** Columns the picker needs. The Person column only yields an email when expanded. */
const REGISTER_SELECT = `ID,${C.rcmInternalNumber},${C.system},${C.status},${C.startDate},${C.engineerName}/Title,${C.engineerName}/EMail`;

/**
 * Lists the register rows so the user can pick one to open. The reader replies with raw
 * SharePoint fields under `{ items: [...] }`; a bare array or `{ value: [...] }` is accepted
 * too, since that is what a "Get items" style flow returns.
 */
export async function listRegisterProjects(readerUrl: string): Promise<RcmRegisterRow[]> {
    const parsed = await postToFlow(readerUrl, {
        action: 'list',
        site: REGISTER_LIST.site,
        list: REGISTER_LIST.list,
        select: REGISTER_SELECT,
        expand: C.engineerName,
        orderBy: 'ID desc',
        top: 500,
    });
    const rows = Array.isArray(parsed) ? parsed
        : Array.isArray(parsed?.items) ? parsed.items
        : Array.isArray(parsed?.value) ? parsed.value
        : null;
    if (!rows) {
        throw new Error(`RCM Register error: expected a list of rows. Raw response: ${JSON.stringify(parsed)}`);
    }
    return rows
        .map((row: any): RcmRegisterRow => {
            const person = row?.[C.engineerName];
            return {
                itemId: Number(row?.ID ?? row?.Id ?? row?.itemId),
                rcmInternalNumber: String(row?.[C.rcmInternalNumber] ?? '').trim(),
                system: String(row?.[C.system] ?? '').trim(),
                status: String(row?.[C.status] ?? '').trim(),
                engineerName: String(person?.EMail || person?.Title || '').trim(),
                startDate: String(row?.[C.startDate] ?? '').trim(),
                jsonFileName: '',
            };
        })
        .filter(row => Number.isFinite(row.itemId));
}

/** Decodes base64 back to text as UTF-8 — the inverse of `toBase64Utf8`. */
export function fromBase64Utf8(base64: string): string {
    const binary = atob(base64.replace(/^data:[^,]*,/, '').trim());
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return new TextDecoder().decode(bytes);
}

/**
 * Downloads the FMECA JSON attachment of one register row through the flow and parses it.
 * Validation that the parsed object really is an FMECA project stays with the caller, which
 * already owns that guard for file imports.
 */
export async function fetchRegisterProjectJson(readerUrl: string, itemId: number): Promise<any> {
    const parsed = await postToFlow(readerUrl, {
        action: 'fetch',
        site: REGISTER_LIST.site,
        list: REGISTER_LIST.list,
        itemId,
        // Publishing attaches both the workbook and the project JSON; match on the suffix so
        // the reader picks the right one without the app knowing the exact file name.
        fileNameEndsWith: '.json',
    });
    const base64 = String(parsed?.contentBase64 ?? parsed?.fileContentBase64 ?? '').trim();
    if (!base64) {
        throw new Error(`RCM Register error: row ${itemId} returned no FMECA JSON attachment. Raw response: ${JSON.stringify(parsed)}`);
    }
    let text: string;
    try { text = fromBase64Utf8(base64); } catch {
        throw new Error(`RCM Register error: the attachment of row ${itemId} is not valid base64.`);
    }
    try { return JSON.parse(text); } catch {
        throw new Error(`RCM Register error: the attachment of row ${itemId} is not valid JSON.`);
    }
}
